# Procedure {#proc}

1. Using data that consists of a time-stamped sequence of shot attempts and outcomes, I will develop a novel analysis using dynamic models for binary time series that allow for time-varying shot attempt and success parameters over the game.  These Bayesian models have core elements that are technically similar to widely used "volatility" models, and have well-known attributes (Prado and West, 2010) (West and Harrison, 1997). This first project component will apply and tune such models to the player-specific data for a series of games or shooting drills. The models provide flexibility in adapting to changes of time intensity of shot attempts, and of changes in time in scoring probabilities conditional on a shot attempt. The use of a formal Bayesian analysis means that I will produce full quantified inferences on such patterns over time, with probabilistic summaries of the within-game outcomes. For each game, this will be a full statistical characterization and quantification of the player shooting outcomes---based on the limited data alone, of course---which across multiple games provides understanding of inherent variability (or "randomness") for the player, and formal assessments of differences in patterns game-to-game. I am also considering a two-state Hidden Markov Switching Model that parallels and extends these models; the two potential states for each shot attempt are a "high" probability or a "low" probability of making the next shot, given the features of the current and previous possessions.

2. If I am given data that adds on-court position for each shot attempt in a game, I will extend the above models to more explanatory, and potentially predictive, dynamic generalized linear models, or DGLMs (West, Migon, and Harrison, 1985) (West and Harrison, 1997), for binary time series. In these models the characterization of variation in shooting behaviour and outcomes will be then linked to time within the game coupled with the x-y location of the player on the shot attempt. For example, two coupled logistic regression DGLMs for binary outcomes will model (a) the probability of a shot attempt being made as a function of both time within the game and of the x-y position of the player, and (b) the probability of success on a shot attempt, conditional on that attempt being made at, as a function of both time and location. Important to the project is the evaluation of dynamic models that allow for and estimate any changes over time within the game in how strongly the x-y location might relate to the attempt and success probabilities. Developing full Bayesian statistical inferences on these patterns over time will be of central interest game-by-game, and this will then feed into cross-game comparisons.