---
title: "Bayesian Analysis of Player Performance over Time"
author: "Nathaniel Brown"
output:
  pdf_document: default
  html_notebook: default
  html_document: default
---

#I. Abstract

The proposed study is an investigation of Bayesian statistical models and analyses for problems arising in shooting a basketball. Goals will be to explore, develop and apply Bayesian models to existing and new data on shooting outcomes, to understand and evaluate questions of inherent random variation, changes over time in shooting performance, and issues related to the "Hot Hand" concept in sports. 

#II. Introduction & Context
<!--(maybe 1 page)-->

The project will define my independent mentored research in completion of the Senior Honor's Thesis requirement for Graduation with Distinction with a Bachelor of Science in Statistical Science at Duke University. I chose this topic because I enjoy basketball, and I want to work with data in a field in which I am knowledgeable and passionate. I gained professional experience in this field as a Data Science Intern with the Oklahoma City Thunder in the summer of 2017. In addition, I have spent the past three years working with records of rudimentary basketball statistics such as counts and shot charts with the Duke Women's Basketball team. Coupled with my academic studies, basketball analytics provides a perfect context for
advancing my expertise in statistical modeling and exploring Bayesian models that are, to my knowledge, new to the 
field. 


#III. Proposal 
<!--(maybe 1 paragraph)-->

A primary goal is to quantify and understand variation over time in player performance linked to shooting attempts. 
I have access to data from shooting drills and film from games and practices from the Duke Women's Basketball team, but I am more interested in accessing SportVU player-tracking data to allow for much more detailed and potentially incisive analyses. The Duke Women's Basketball data would require manual entry and updates, and it would provide less information than the SportVU cameras. Specifically, I am interested in accessing SportVU data that includes both player tracking information and the corresponding play-by-play information, such as the time of shot attempts according to the game clock, and the players' locations at the times of the shots. The project will require such data of a series of games. 
I will need no more than one season of games, but I ask that the included games are consecutive so that I can analyze game-to-game trends. I would like to access this fine-scale data for just one player for the purposes of this project. It would be
best to have this be a prolific shooter and over as many consecutive games in one season as possible. Historical data 
is of course requested, and anonymization of the player and games/opponents will not at all impact on my 
research and statistical analyses. 

Which specific models and analyses I develop will depend on the data provided. 

1. First, with data on one player in one game providing time-stamped shot attempts and outcomes, I will develop a novel analysis using dynamic models for binary time series that allow for time-varying shot attempt and success parameters over the game. These Bayesian models have core elements are technically similar to widely used "volatility" models (used in finance, for example), and have well-known attributes (Prado and West, 2010) (West and Harrison, 1997). This first project component will apply and tune such models to the player-specific data for each of a series of games.  The models provide flexibility in adapting to changes of time intensity of shot attempts, and of changes in time in scoring probabilities conditional on a shot attempt. The use of a formal Bayesian analysis means that I will produce full quantified inferences on such patterns over time, with probabilistic summaries of the within-game time trajectories.  For each game, this will be a full statistical characterization and quantification of the player shooting outcomes---based on the limited data alone, of course---which across multiple games provides understanding of inherent variability ( or "randomness") for the player, and formal assessments of differences in patterns game-to-game. I am also considering a two-state Hidden Markov Switching Model that   parallels and extends these models; the two potential states for each shot attempt are a "high" probability or a "low" probability of making the next shot, given the features of the current and previous possessions.


2. Second, and of much more interest and potential value, will be data that adds to the above the information on court position for each shot attempt.  With such additional data, I will extend the above models to more explanatory, and potentially predictive, dynamic generalized linear models, or DGLMs (West, Migon, and Harrison, 1985) (West and Harrison, 1997), for binary time series. In these models the characterization of variation in shooting behaviour and outcomes will be then linked to time within the game coupled with the x-y location of the player on the shot attempt.  For example, two coupled logistic regression DGLMs for binary outcomes will model (a) the probability of a shot attempt being made as a function of both time within the game and of the x-y position of the player, and (b) the probability of success on a shot attempt,  conditional on that attempt being made at, as a function of both time and location. 
 Important to the project is the evaluation of $\textit{ dynamic models}$ that allow for and estimate any changes over time within the game in how strongly the x-y location might relate to the attempt and success probabilities. Developing full Bayesian statistical inferences on these patterns over time will be of central interest game-by-game, and this will then feed into cross-game comparisons. 


3. Any additional data provided could be explored and incorporated into models above in the same way as court location is treated (i.e., as potential predictor variables that have some role in explaining changes over time within a game and between games). Some data such as the style of shot attempt (e.g., left hand, right hand, jump shot, dunk, etc). In addition to potentially explaining observed variation,  including such data in extended models could the yield inferences on how such shot characteristics change over time and game-to-game. 





#IV. Outcomes

 The project will result in a written Senior Honors thesis in the form of an academic paper, together with code I develop for several models and analyses.  I aim to develop the paper as potentially publishable in a statistical journal. The project will also define a main educational experience for me, building my expertise in Bayesian statistical modeling for time-dependent data, and and in independent research. 

Potential outcomes for the Thunder include insights in modelling trends and variability in player performance, both within games and between games. Building these models on data that belongs to the Thunder means that they will have an advantage in implementing this analysis if they find the results useful or interesting.


#V. References

Albert, J. (1993). A Statistical Analysis of Hitting Streaks in Baseball: Comment. $\textit{Journal of the American}$   $\textit{Statistical Association}$, ${\bf 88}$(424), 1184-1188.

Albert, J. (2013). Looking at Spacings to Assess Streakiness. $\textit{ Journal of Quantitative Analysis in Sports}$, ${\bf 9}$(2), 1-13.

Albert, J., & Williamson, P. (2001). Using model/data simulations to detect streakiness. $\textit{ The American Statistician}$, ${\bf 55}$, 41-50.

Bar-Eli, M., Avugos, S., & Raab, M. (2006). Twenty Years of "Hot Hand" Research: Review and Critique. $\textit{ Psychology of Sports and Exercise}$, ${\bf 7}$, 525-553.

Gilovich, T., Vallone, R., & Tversky, A. (1985). The Hot Hand in Basketball: On The Misperception of Random Sequences. $\textit{ Cognitive Psychology}$, ${\bf 17}$, 295-314.

Jagacinski, R. J., K. M. Newell, and P. D. Isaac. (1979). Predicting the Success of a Basketball Shot at Various Stages of Execution. $\textit{ Journal of Sport Psychology}$, ${\bf 1}$, 301-310.

Koehler, J. J., & Conley, C. A. (2003). The "Hot Hand" Myth in Professional Basketball. $\textit{ Journal of Sport and Exercise Psychology}$, ${\bf 25}$, 253-259.

Miller, J. B., Sanjurjo, A. (2016). Surprised by the Gambler's and Hot Hand Fallacies? A Truth in the Law of Small Numbers. IGIER Working Paper No. 552. 

Prado, R., West, M. (2010). $\textit{Time Series: Modeling, Computation, and Inference}$. London: Chapman & Hall/CRC Press.

West, M., Harrison, P.J. (1997). $\textit{Bayesian Forecasting \& Dynamic Models}$. Berlin: Springer Verlag.
<!-- Bayesian Forecasting & Dynamic Models -->

Wetzels, R. et. al., (2016). A Bayesian Test for the Hot Hand Phenomenon. $\textit{Journal of Mathematical Psychology}$, ${\bf 72}$, 200-209.
